version: '3.7'

services:
  back:
    container_name: backend-container
    image: abdelhaq22/e-learning:backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
    depends_on:
      - db

  front:
    container_name: frontend-container
    image: abdelhaq22/e-learning:frontend
    build:
      context: ../Interfaces
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PORT=3000
      - REACT_APP_API=8080
    depends_on:
      - back

  db:
    container_name: mongodb-container
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_DB=abdo
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
    external: true
